version: "3.8"

services:
  app: 
    image: greymint-auth:0.0.1
    container_name: app
    restart: always
    depends_on:
      - mongo
    ports:
      - 3000:8000 # host to container
    environment:
      - ENV=${ENV}
      - ALGORITHM=${ALGORITHM}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PWD=${MONGO_PWD}

  
  mongo:
    image: mongo:5.0.11
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PWD}
      - MONGO_INITDB_DATABASE=${MONGO_DB}
    volumes:
      - ./mongo_init.js:/docker-entrypoint-initdb.d/mongo_init.js
